spring.application.name=localloop

server.port=${PORT:5000}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}    
jwt.expiration=86400000


logging.level.org.springframework.boot.context.properties=TRACE
logging.level.com.zaxxer.hikari=DEBUG
debug=true